{"name": "test_div[get_div_datas1]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0.5 == 2", "trace": "self = <test_calc_new.TestCalc object at 0x7f25447d6d60>, get_calc = <pythoncode.calculator.Calculator object at 0x7f25447b1310>\nget_div_datas = [-1, -2, 2]\n\n    @pytest.mark.run(order=4)\n    # 测试div函数\n    def test_div(self, get_calc, get_div_datas):\n        try:\n            # 调用div函数，返回的结果保存在result里面\n            result = get_calc.div(get_div_datas[0], get_div_datas[1])\n            if isinstance(result, float):\n                result = round(result,2)\n        except Exception as e:\n            print(e)\n        #判断result结果是否等于期望的值\n>       assert result == get_div_datas[2]\nE       assert 0.5 == 2\n\ntest_calc_new.py:33: AssertionError"}, "attachments": [{"name": "stdout", "source": "57f60ae8-f2d2-484a-a7ac-443853d0ad95-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "get_div_datas", "value": "[-1, -2, 2]"}], "start": 1609517343009, "stop": 1609517343010, "uuid": "ad99d7d2-b1c8-41ad-931c-4e449465f7e8", "historyId": "5ff4920cd9bc0ae98a9a5ee1d8fd8600", "testCaseId": "b433a02ec13245ef6dd3b014f7c89e96", "fullName": "pytestwork2.test_calc_new.TestCalc#test_div", "labels": [{"name": "tag", "value": "run(order=4)"}, {"name": "parentSuite", "value": "pytestwork2"}, {"name": "suite", "value": "test_calc_new"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "ygl-virtual-machine"}, {"name": "thread", "value": "16108-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "pytestwork2.test_calc_new"}]}